# SPDX-FileCopyrightText: 2023 Chris Wilson <chris@cgnd.dev>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-executables-have-shebangs
  - id: check-symlinks
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
- repo: https://github.com/fsfe/reuse-tool
  rev: v1.1.2
  hooks:
  - id: reuse
