# SPDX-FileCopyrightText: 2023 Chris Wilson <chris@cgnd.dev>
#
# SPDX-License-Identifier: MIT

- id: zephyr-checkpatch
  name: Run Zephyr's checkpatch.pl
  description: This hook runs the `${ZEPHYR_BASE}/scripts/checkpatch.pl` script on on C source files.
  entry: bash -c 'git diff --cached | "${ZEPHYR_BASE}"/scripts/checkpatch.pl -' --
  language: system
  types: [c]
  pass_filenames: false
